### ISSUE TITLE
mg_stop() waits until websocket clients disconnect on their own

### ISSUE THREAD

**Issue by celeron55** [bel2125/civetweb#77] opened 2015-03-19 09:10 UTC
I am using websocket connections, and when I call mg_stop() on the server, it will not stop until the clients have disconnected by themselves or attempted to send data after mg_stop(). Some of the clients are using civetweb's mg_connect_websocket_client(), and some are web browsers.

This old issue seems to match the behavior: https://code.google.com/p/mongoose/issues/detail?id=268

I am able to fix the problem on GNU/Linux by doing something like this: (alternatively using select() or poll() would also work)

	diff --git a/3rdparty/civetweb/civetweb.c b/3rdparty/civetweb/civetweb.c
	index 9c50bb6..1b9853b 100644
	--- a/3rdparty/civetweb/civetweb.c
	+++ b/3rdparty/civetweb/civetweb.c
	@@ -2454,7 +2454,13 @@ static int pull(FILE *fp, struct mg_connection *conn, char *buf, int len)
		     nread = SSL_read(conn->ssl, buf, len);
	 #endif
		 } else {
	-        nread = recv(conn->client.sock, buf, (size_t) len, 0);
	+               nread = -1;
	+        while(conn->ctx->stop_flag == 0){
	+            nread = recv(conn->client.sock, buf, (size_t) len, 0);
	+            if(nread == -1 && (errno == EAGAIN || errno == EWOULDBLOCK))
	+                continue;
	+            break;
	+        }
		 }
	 
		 return conn->ctx->stop_flag ? -1 : nread;
	@@ -7307,6 +7313,17 @@ static void process_new_connection(struct mg_connection *conn)
	 
		 keep_alive_enabled = !strcmp(conn->ctx->config[ENABLE_KEEP_ALIVE], "yes");
	 
	+    // Enable read timeouts on the socket
	+    {
	+        struct timeval t;
	+        t.tv_sec = 1;
	+        t.tv_usec = 0;
	+        if (setsockopt(conn->client.sock, SOL_SOCKET, SO_RCVTIMEO,
	+                (char *)&t,  sizeof(t))) {
	+            mg_cry(conn, "%s: setsockopt(SO_RCVTIMEO) failed", __func__);
	+        }
	+    }
	+
		 /* Important: on new connection, reset the receiving buffer. Credit goes
		    to crule42. */
		 conn->data_len = 0;

**Comment by bel2125** [comment] 2015-03-19 20:04
This old mongoose issue was still fixed in MIT code, before the mongoose license changed to GPL/commercial and before Civetweb was created to maintain the MIT license. So it it is really this issue, it should be fixed - although I have not really checked this myself.

That time in 2012 I had my own clone where this was fixed before it was fixed in the main stream:
https://code.google.com/r/bel2125-mongoose/source/browse/mongoose.c#4293
Your second change in process_new_connection is pretty much the same as this old fix which is not in the first lines of process_new_connection just a few lines before process_new_connection is called.
It would not be a problem to add a call to set_sock_timeout there - I just wonder it is still required.

I also wonder why the change in pull is required for the exit problem - recv falls out of the timeout, and return conn->ctx->stop_flag ? -1 : nread; makes the server stop.

I would like to reproduce this problem, in order to understand it.
I can not reproduce it with my websocket clock example in the test directory. Can you reproduce it with them?
What system are you using?
How did you set the request_timeout_ms parameter?

**Comment by celeron55** [comment] 2015-03-21 20:50
I can't find a "clock" example anywhere; can you point me to it?

Without the addition in pull(), the websocket server will disconnect the clients after the timeout because recv() returns -1, which normally is an error and broken socket, but in this case with errno=EAGAIN or EWOULDBLOCK it means there just wasn't anything to receive during the timeout.

**Comment by bel2125** [comment] 2015-03-21 21:02
> I can't find a "clock" example anywhere; can you point me to it?

https://github.com/bel2125/civetweb/blob/master/test/websocket.xhtml
with https://github.com/bel2125/civetweb/blob/master/test/websocket.lua

**Comment by celeron55** [comment] 2015-03-22 09:15
...how do I run that? Setting document_root to "test" doesn't seem to do it, and the user manual doesn't really tell anything useful. I have never run any Lua stuff with civetweb.

**Comment by bel2125** [comment] 2015-03-22 19:24
for Linux:

change to the civetweb directory

    make WITH_LUA=1 WITH_WEBSOCKET=1

    ./civetweb -document_root test/

then open http://localhost:8080/websocket.xhtml

The browser (if it is not too outdated) will show an analog clock (i.e., a circle with two arrows) and in the middle a digital clock with hours (0-23), minutes and seconds.

If you have a look at the xhtml file, you will see there is actually no clock implemented, but just some SVG drawing primitives for a circle, two arrows and a text field. The direction for the arrows, to make them clock hands showing, as well as the text in the center are received from a websocket connection (the 'connection.onmessage' is the client side of the websocket):
https://github.com/bel2125/civetweb/blob/master/test/websocket.xhtml#L51

The server side of the websocket is in websocket.lua. The time data (angles for the clock hands and text for the digital clock) is sent by the 'senddata' function:
https://github.com/bel2125/civetweb/blob/master/test/websocket.lua#L92

Now, when you see the clock running in the browser, switch back to the Linux shell you started ./civetweb
Hit Ctrl-C once to stop the server. You will see a line like

> Exiting on signal 2, wait for all threads to finish ...

https://github.com/bel2125/civetweb/blob/master/src/main.c#L1681
A few lines later mg_stop(ctx) is called.

This is exactly the situation, you have, right?
A websocket connection is still open, while the server is about to exit.
Now it will indeed take several seconds until the websocket connections are properly closed. You will that the server closed the connection correctly by a message "end" in the center of the clock shown in the browser.

The server will show 

> Exiting on signal 2, wait for all threads to finish ... done.

and end. I would consider this as a test of a perfectly clean shutdown of the websocket connection on shutdown of the server. It works not only for Linux but also for Windows: Instead of pushing Ctrl-C, the server is stopped from the context menu.

With these successful tests, I thought there is no problem with a shutdown when a websocket connection is open. That's why I would like to reproduce this problem, in order to understand it.

**Comment by bel2125** [comment] 2015-03-22 21:43
Looking again at the first part of the patch:

    -    nread = recv(conn->client.sock, buf, (size_t) len, 0);

    +    nread = -1;
    +    while (conn->ctx->stop_flag == 0) {
    +        nread = recv(conn->client.sock, buf, (size_t) len, 0);
    +        if (nread == -1 && (errno == EAGAIN || errno == EWOULDBLOCK)) 
    +            continue;
    +        break;
    +    }


According to http://linux.die.net/man/2/recv

> a receive timeout had been set and the timeout expired before data was received.

This would actually override the timeout in any other case except exit of the server. So you would block the entire connection if a client is gone without a clean shutdown from the client side. If you run the server on one computer, open 50 websocket connections from a second one, then unplug the network cable between them and reboot the second computer. Then the server can no longer be reached, because it still has 50 connections that run in this loop.
I did not actually test this with that particular fix, but I know it existed before there were these timeouts. I expect this problem to occur again if a client timeout does not lead to closing the connection to the client.

**Comment by celeron55** [comment] 2015-03-23 00:22
Okay now it runs; I originally forgot to compile with USE_WEBSOCKET=1.

Given that I comment out `connection.send('client still alive');` from the client side, I can replicate my problem with this command:
`./civetweb -document_root test -request_timeout_ms 60000`

When you press CTRL+C, what will happen is that the server will wait for the full duration of request_timeout_ms before shutting down. The server will shut down instantly if the client sends anything during that waiting period, which is why the keep-alive message has to be commented out.

What I expect to happen is that when mg_stop() is called, all of civetweb's blocking calls are made to return within a few seconds independently of any request timeouts or user-made keepalive intervals so that my program can exit gracefully.

Setting the timeout like in my workaround/example is probably dumb from many standpoints, none of which happen to matter in my use case. Like I said, poll()/select() generally makes more sense.

**Comment by bel2125** [comment] 2015-05-10 21:35
@celeron55: I can't remember: did I actually already fix this and just forgot to close the issue, or did I leave some important TODO and forgot what it was?

Did you do a test recently?

**Comment by celeron55** [comment] 2015-05-12 18:48
I'll try to take a new look at this in a few weeks.

**Comment by celeron55** [comment] 2015-05-21 08:28
Okay, so, after going through the recent callback API changes, I have now tested that this issue still exists just as it did before, and I can personally get rid of the problem with exactly the same ugly modifications.

**Comment by bel2125** [comment] 2015-05-21 22:14
I will have a look again during the weekend.

**Comment by bel2125** [comment] 2015-05-26 20:38
I tested it again in Win32 and Linux (Ubuntu 64 bit), both with the Websocket in Lua.
I used the test page with the keep-Alive extension I made for this test in April.

https://localhost/websocket.xhtml?keepAlive=f

The keepAlive=f corresponds to commenting out the `connection.send('client still alive');` line (see https://github.com/bel2125/civetweb/blob/master/test/websocket.xhtml#L61), so this test should correspond to the test you made above:


> Given that I comment out `connection.send('client still alive');` from the client side, 
> I can replicate my problem with this command:
> `./civetweb -document_root test -request_timeout_ms 60000`

In both cases (Linux and Windows) the server stops in less than 10 seconds.

Before I apply a patch, I want to reproduce the problem and investigate possible side effects, e.g. other timeouts that do no longer work properly then.

**Comment by celeron55** [comment] 2015-05-28 08:57
Oh. Looks like it does actually work now. I have no idea what might have gone wrong when I tested.

It's certainly slow to my tastes though, taking up to 10 seconds to shut down which makes test cycles while developing slow. Would there be a chance to have a compile-time or runtime parameter to make it quicker?

**Comment by bel2125** [comment] 2015-05-28 20:04
One option that should already work is to set `request_timeout_ms` down to one second. Then also exit of the server should be after one second.

The changes I made in April were just if `request_timeout_ms` is more than 10 seconds, still a 10 seconds timeout is used, so the server can exit after this time.

For a regular use, 10 seconds seemed fast enough for me (I would be happy if some of my standard Windows applications would only require 10 seconds to close). A shorter time just leads to unnecessary task wake-ups during the normal operation - so 10 seconds seemed a meaningful value. I also think it does not make much sense to configure this in the final server, since this config parameter is of no use for the regular operation.

... that's all for the final server, having a compile time parameter for development is a different topic.
But still, if a compile time parameter is officially supported, it should also be tested.
If you only need it for development, and you are building the server on your own (which is the case for Linux anyway), have a loop at the following lines: https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L9422 (line numbers are subject to change, so it might be a few lines up or down in a few days) - just change the 10000 to 1000 in both lines, and test if it fulfills your needs:

		if ((timeout > 0) && (timeout < 10000)) {
			set_sock_timeout(so.sock, timeout);
		} else {
			set_sock_timeout(so.sock, 10000);
		}

**Comment by bel2125** [comment] 2015-05-28 21:36
> One option that should already work is to set request_timeout_ms down to one second. Then also exit of the server should be after one second.

As a side effect, that the client needs to send data to the server every second.
Since this is unacceptable, I need an additional configurable timeout for websockets anyway - but not a configurable timeout for server exit.

**Comment by celeron55** [comment] 2015-05-29 11:42
Well, I already modified my copy to have 2000 in there in place of 10000. :-)

I understand that for actual production use 10 seconds is probably reasonable (maybe; altough I do think practically all web servers exit faster than that in all cases). I don't think it would be that bad to have it as a constant defined by the build system, but if you choose not to want to maintain it, I'm fine with doing this change myself when developing my thing.

**Comment by bel2125** [comment] 2015-05-29 18:12
If you tested it and it works, I can also add the compile variable. Most likely this will work for years.
I just don't want to test different values in every version and check if a timeout of 1.46 seconds is really 1.46 seconds. I can add if when I need to change the websocket timeout anyway.

**Comment by bel2125** [comment] 2015-05-30 11:50
SOCKET_TIMEOUT_QUANTUM (Suggestions for a better name?)
https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L184
Not tested by me with anything <> 10000

**Comment by xtne6f** [comment] 2015-06-03 14:56
On Windows, current civetweb often falls into busy-wait in pull() till the timeout if a connection is closed by a client ( `nread == -1` and `errno == ENOENT(2)` ).
This behavior must be caused by 86ac7a404fa6cf03fb02897d23b25c3a389f5928, are you going to fix it?

**Comment by bel2125** [comment] 2015-06-03 18:44
> are you going to fix it?

Sure.
I am currently working on the timeouts in both, push and pull - the changes are just not ready to be merged into the official repository yet.

**Comment by xtne6f** [comment] 2015-06-04 14:32
Thank you.
I confirmed that 0589118f27598b998c211a743262ea945d104a66 solved my busy-wait issue completely.

**Comment by bel2125** [comment] 2015-06-17 19:25
I think everything here is already fixed, so I will close this issue.
If something similar reappears, please open a new issue.

**Closed by bel2125** 2015-06-17 19:25 UTC
