### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by gladkikhartem** [bel2125/civetweb#119] opened 2015-05-06 22:04 UTC
Importance: LOW

I've come in trouble with a couple of issues while compiling and running cywetweb on Windows.
1. Using 443s port (SSL enabled) i have 100% CPU Load.
civitweb does not close connection properly  in function:
static int pull(FILE *fp, struct mg_connection *conn, char *buf, int len)
......
#ifndef NO_SSL
        } else if (conn->ssl != NULL) {
            nread = SSL_read(conn->ssl, buf, len);
#endif
........
conn->ssl is NULL, while this is HTTPS socket. this causes infinite loop eating up CPU.
My solution was to use only SSL port and return -1 when conn->ssl is null.

2. Using IPv6 addresses in config causes app co crash. :
DEFINES += USE_IPv6

and add  missing windows functions: 

const char *inet_ntop(int af, const void *src, char *dst, socklen_t cnt)
{
        if (af == AF_INET)
        {
                struct sockaddr_in in;
                memset(&in, 0, sizeof(in));
                in.sin_family = AF_INET;
                memcpy(&in.sin_addr, src, sizeof(struct in_addr));
                getnameinfo((struct sockaddr *)&in, sizeof(struct
sockaddr_in), dst, cnt, NULL, 0, NI_NUMERICHOST);
                return dst;
        }
        else if (af == AF_INET6)
        {
                struct sockaddr_in6 in;
                memset(&in, 0, sizeof(in));
                in.sin6_family = AF_INET6;
                memcpy(&in.sin6_addr, src, sizeof(struct in_addr6));
                getnameinfo((struct sockaddr *)&in, sizeof(struct
sockaddr_in6), dst, cnt, NULL, 0, NI_NUMERICHOST);
                return dst;
        }
        return NULL;
}

int inet_pton(int af, const char *src, void *dst)
{
        struct addrinfo hints, *res, *ressave;

        memset(&hints, 0, sizeof(struct addrinfo));
        hints.ai_family = af;

        if (getaddrinfo(src, NULL, &hints, &res) != 0)
        {
                return -1;
        }

        ressave = res;

        while (res)
        {
                memcpy(dst, res->ai_addr, res->ai_addrlen);
                res = res->ai_next;
        }

        freeaddrinfo(ressave);
        return 0;
}

and add to line 7035:
        so->lsa.sin6.sin6_family = AF_INET6;
        so->lsa.sin6.sin6_port = htons((uint16_t) port);

This allows to open ipv6 socket listening INADDR_ANY to all connections, and then IPv6 on Windows is working fine.

**Comment by bel2125** [comment] 2015-05-08 20:22
What version of civetweb are you using?
What version of Windows?

> and add to line 7035:
> so->lsa.sin6.sin6_family = AF_INET6;
> so->lsa.sin6.sin6_port = htons((uint16_t) port);

Line 7035 is currently in the middle of a variable declaration block in `set_ports_option`:
https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L7035

Before it was hust before a memset of so to 0:
https://github.com/bel2125/civetweb/blob/13f488bbd6c2c82a89d488532330629bc500005e/src/civetweb.c#L7035
And so is a structure here, not a pointer, so `so->something` can not be correct here.

What line do you mean? What function, what code is before and after?

**Comment by gladkikhartem** [comment] 2015-05-09 10:56
What version of civetweb are you using?

The trunk one. i.e. latest.


What version of Windows?

Win 7 x64.

I'm sorry for wrong line code mentioned, i've forgot that i've added
declarations at top.

it's this line
https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L7010,

right after  comment  /* If only port is specified, bind to IPv4,
INADDR_ANY */

the block that handles only port number input.


Thank for reply!


P.S

This fix is not important as i've finished integration (CivetWeb works
perfect!!!), but it could help you to integrate IPv6 support for Windows.
Basic port binding should be enough i think, as not so many people will
bind to specific IPv6 address.


2015-05-09 2:22 GMT+06:00 bel2125 <notifications@github.com>:

> What version of civetweb are you using?
> What version of Windows?
>
> and add to line 7035:
> so->lsa.sin6.sin6_family = AF_INET6;
> so->lsa.sin6.sin6_port = htons((uint16_t) port);
>
> Line 7035 is currently in the middle of a variable declaration block in
> set_ports_option:
> https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L7035
>
> Before it was hust before a memset of so to 0:
>
> https://github.com/bel2125/civetweb/blob/13f488bbd6c2c82a89d488532330629bc500005e/src/civetweb.c#L7035
> And so is a structure here, not a pointer, so so->something can not be
> correct here.
>
> What line do you mean? What function, what code is before and after?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bel2125/civetweb/issues/119#issuecomment-100351739>.
>



-- 
Best regards, Gladkikh Artem

**Comment by bel2125** [comment] 2015-05-10 21:27
I merged some of the fixes above.

This seems to cause a problem:

> and add to line https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L7054:
> so->lsa.sin6.sin6_family = AF_INET6;
> so->lsa.sin6.sin6_port = htons((uint16_t) port);

Since this will overwrite binding to IPv4, so the server will only bind to IPv6.
And if you have IPv6 disabled, the server will fail to start.

Probably there is a new config required to tell the server to bind to an IPv6 port instead of IPv4:
  - 1.2.3.4:1234 will tell the server to bind to port 1234 a specific IP v4 adapter with address (1.2.3.4)
  - [1:2:3:4:5:6:7:8] :2345 will tell the server to bind to port 2345 of the given IP v6 adapter
  - 3456 will tell the server to bind to port 3456 of every IPv4 address network adapter
  - everything else is an error. 
Thus, binding to every adapter address on IPv6 is currently missing, right?


I still did not have a look at this:

> Using 443s port (SSL enabled) i have 100% CPU Load.
civitweb does not close connection properly in function:
static int pull(FILE *fp, struct mg_connection *conn, char *buf, int len)
......
#ifndef NO_SSL
} else if (conn->ssl != NULL) {
nread = SSL_read(conn->ssl, buf, len);
#endif
........
conn->ssl is NULL, while this is HTTPS socket. this causes infinite loop eating up CPU.
My solution was to use only SSL port and return -1 when conn->ssl is null.


I will do that later and first try to reproduce the problem. Did you have to do anything special to reproduce it?

**Comment by gladkikhartem** [comment] 2015-05-11 10:42
Oh, i see your logic, didn't thought about that.

About second issue - there's no special things i've did  - just compiled
demo with MinGW and QT Creator, copied SSL dlls to the root and added ssl
port and certificates to the config in the code.
Whenever one opens https page - one thread starting to consume 100% of CPU
power. (I have 4 core, so it take 25% of cpu).
It consumes CPU till timeout for the socket is reached.



2015-05-11 3:27 GMT+06:00 bel2125 <notifications@github.com>:

> I merged some of the fixes above.
>
> This seems to cause a problem:
>
> and add to line
> https://github.com/bel2125/civetweb/blob/master/src/civetweb.c#L7054:
> so->lsa.sin6.sin6_family = AF_INET6;
> so->lsa.sin6.sin6_port = htons((uint16_t) port);
>
> Since this will overwrite binding to IPv4, so the server will only bind to
> IPv6.
> And if you have IPv6 disabled, the server will fail to start.
>
> Probably there is a new config required to tell the server to bind to an
> IPv6 port instead of IPv4:
>
>    - 1.2.3.4:1234 will tell the server to bind to port 1234 a specific IP
>    v4 adapter with address (1.2.3.4)
>    - [1:2:3:4:5:6:7:8] :2345 will tell the server to bind to port 2345 of
>    the given IP v6 adapter
>    - 3456 will tell the server to bind to port 3456 of every IPv4 address
>    network adapter
>    - everything else is an error. Thus, binding to every adapter address
>    on IPv6 is currently missing, right?
>
> I still did not have a look at this:
>
> Using 443s port (SSL enabled) i have 100% CPU Load.
> civitweb does not close connection properly in function:
> static int pull(FILE *fp, struct mg_connection *conn, char *buf, int len)
> ......
> #ifndef NO_SSL
> } else if (conn->ssl != NULL) {
> nread = SSL_read(conn->ssl, buf, len);
> #endif
> ........
> conn->ssl is NULL, while this is HTTPS socket. this causes infinite loop
> eating up CPU.
> My solution was to use only SSL port and return -1 when conn->ssl is null.
>
> I will do that later and first try to reproduce the problem. Did you have
> to do anything special to reproduce it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bel2125/civetweb/issues/119#issuecomment-100703812>.
>



-- 
Best regards, Gladkikh Artem

**Comment by grunk** [comment] 2015-06-10 13:08
I had a similar issue (100% CPU with SSL). 
I fixed it by doing this : 
```c
#ifndef NO_SSL
	} else if (conn->ssl != NULL) {
		nread = SSL_read(conn->ssl, buf, len);
	}
	//Here the fix
	else if(conn->client.is_ssl && conn->ssl == NULL)
	{
		return -1;
#endif
	} else {
		nread = (int)recv(conn->client.sock, buf, (size_t) len, 0);
	}
```

This morning i have updated civet and the fix don't seems to be needed anymore. I was at least 60 commits behind (don't remember exactly) but it's seems to be good to me right now.
@gladkikhartem did you try to update recently ?

**Comment by bel2125** [comment] 2015-06-10 19:13
The busy wait issue should have been gone when I rewrote push/pull recently: https://github.com/bel2125/civetweb/commit/0589118f27598b998c211a743262ea945d104a66
See also this comment (https://github.com/bel2125/civetweb/issues/77#issuecomment-108916048) on #77.

But of course you should test it again in your cases.

The other issue here was how to bind to an IPv6 port for all interfaces.
The missing syntax would be `[::]:8080` (see the upper half of https://github.com/bel2125/civetweb/issues/119#issuecomment-100703812)

**Comment by gladkikhartem** [comment] 2015-06-11 06:41
Thanks in advance!
I've tested the new sources and the issue has gone!

P.S.  you have the easiest webserver to embed on the whole internet))).

2015-06-11 1:13 GMT+06:00 bel2125 <notifications@github.com>:

> The busy wait issue should have been gone when I rewrote push/pull
> recently: 0589118
> <https://github.com/bel2125/civetweb/commit/0589118f27598b998c211a743262ea945d104a66>
> See also this comment (#77 (comment)
> <https://github.com/bel2125/civetweb/issues/77#issuecomment-108916048>)
> on #77 <https://github.com/bel2125/civetweb/issues/77>.
>
> But of course you should test it again in your cases.
>
> The other issue here was how to bind to an IPv6 port for all interfaces.
> The missing syntax would be [::]:8080 (see the upper half of #119
> (comment)
> <https://github.com/bel2125/civetweb/issues/119#issuecomment-100703812>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bel2125/civetweb/issues/119#issuecomment-110882313>.
>



-- 
Best regards, Gladkikh Artem

**Comment by bel2125** [comment] 2015-06-18 19:22
I think everything here is done now, right?

**Comment by gladkikhartem** [comment] 2015-06-18 19:40
Yep, we can mark issue as Solved.

2015-06-19 1:22 GMT+06:00 bel2125 <notifications@github.com>:

> I think everything here is done now, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bel2125/civetweb/issues/119#issuecomment-113264456>.
>



-- 
Best regards, Gladkikh Artem

**Comment by bel2125** [comment] 2015-06-18 19:44
Everything is fixed.

**Closed by bel2125** 2015-06-18 19:44 UTC
