### ISSUE TITLE
Civetweb listening port will change if start more than 150 Civetweb instance on one machine(win7 64bit)

### ISSUE THREAD

**Issue by hanrobin123** [bel2125/civetweb#142] opened 2015-06-09 13:50 UTC
For example, we start Civetweb1  listening on 50000,   Civetweb2  listening on 50001 ... and so on.
if the number of Civetweb less than 100, every thing looks ok. If the number of Civetweb instance is more than 150, the listening port will change. Civetweb1  may listen on 60000 for example.
Another issue is one Civetweb instance may listen on multi ports. For instance, I specify port number 50000 for Civetweb1. As result, Civetweb1 listen on 50000 and 51000 at the same time. 
Is this a known issue? Thank you.

**Comment by bel2125** [comment] 2015-06-09 19:08
No, this is not known to me yet.
I have never started more than a maybe 3 to 5 instances on the same machine.

How do you test this exactly:
    civetweb_lua.exe -listening_ports 50000 -document_root r:\0\ -title 0
    civetweb_lua.exe -listening_ports 50001 -document_root r:\1\ -title 1
    civetweb_lua.exe -listening_ports 50002 -document_root r:\2\ -title 2
    ...
    civetweb_lua.exe -listening_ports 50150 -document_root r:\150\ -title 150
and then ... which of these 151 instances uses the wrong port?

**Comment by bel2125** [comment] 2015-06-09 19:26
I started it this way (with an interactive Lua interpreter) - but on Windows 32 bit Machine which did not open more than 85 instances, and displayed an error message box for the other instances ("cannot bind ... bad file descriptor"). The 85 instances work.

    > for i=0,150 do
    >> os.execute([[mkdir r:\]] .. i .. [[\]])
    >> os.execute([[echo ]] .. i .. [[ > r:\]] .. i .. [[\]] .. i .. [[.txt]])
    >> os.execute([[
    >> start D:\civetweb\VS2012\Debug\Win32\civetweb_lua.exe -listening_ports ]] .. (50000+i) .. [[ -document_root r:\]] .. i .. [[ -title ]] .. i)
    >> end

I have a Win8 64 bit machine as well, but before I do a lot of tests, please explain me in more detail what you did to get the error.

**Comment by hanrobin123** [comment] 2015-06-10 14:24
Thank you for the quick reply. The civeweb was embedded in our win32 application(say A.exe). We use java application to start more than 150 A.exe(each of them listening on unique port, for example from 50000 to 50150) by java API Runtime.exec("A.exe").  Sometime later, some civeweb instance embedded in A.exe will listen on other port like 60000, 60100 etc. 
The code in A.exe to start civeweb looks like below:

const char *options[] =
     {
           "document_root", "./web",
           "listening_ports", "50000",
           "num_threads", "5",
           "access_log_file", accessLogFullPath.c_str(),
           "error_log_file", errLogFullPath.c_str(),
           nullptr
     };

     std::string docRoot = GSE.GetDocRoot().WideToStr().get();
     if (!docRoot.empty())
     {
           options[1] = docRoot.c_str();
     }

     const char* port = getenv("GS_PORT");
     if (port != NULL)
     {
           options[3] = port;
     }
     String strMsg;
     strMsg = _T("Actual GSPORT is :");
     strMsg +=  options[3];

     const char* threads = getenv("GS_THREADS");
     if (threads != NULL)
     {
           options[5] = threads;
     }
     // Start the web server.
     mg_callbacks callbacks = {0};
     g_initWebSocketHandler(&callbacks);
     m_ctx = mg_start(&callbacks, this, options);
     if (m_ctx == nullptr)
     {
           throw CWebServerException(ooInvalidAction, "Could not start web server, function mg_start returned an error.");
     }
     mg_set_request_handler(m_ctx, "/", Dispatch, 0);

**Comment by bel2125** [comment] 2015-06-10 18:33
You started 151 instances, listening to port 50000 to port 50150?
You checked all 151 `strMsg`, that the right port has been opened?
Then you wait some time? How long?
And then, the instances, that listened to port 50000 before now listens to port 60000?

**Comment by hanrobin123** [comment] 2015-06-10 23:50
Yes. I started 151 instances, listening to port 50000 to port 50150. From the strMsg, the input port is right.
after about 20 or more minutes, then the issue appears. it will listen on other port id instead of the original port it.

**Comment by bel2125** [comment] 2015-06-20 20:23
I started 1000 servers on an Ubuntu Linux 64 bit system, IPv4 port 50000 to port 50999.
Each server instance uses a different `-document_root` `/tmp/000/`, `/tmp/001` to `/tmp/999`. I created 1000 files before: `/tmp/000/000.txt`, `/tmp/001/001.txt` to `/tmp/999/999.txt`.
From another PC, I tested it with `curl http://1.2.3.4:50???` (spot tests) for several hours, and checked if the reply shows a file with a name corresponding to the port.
There was no problem (beside the Ubuntu desktop became a bit slow due to the load of the 1000 servers, but the server responded quickly). There was no port problem.

Then I did the same on a Windows 8 64 bit system. Port 50000 seems to be used by the system, so I used 20000 to 20999, but otherwise the same test setup. It again worked well with this port range.

I checked that port 50000 overlaps with the ephemeral port range or Windows 7 and Windows 8 (https://en.wikipedia.org/wiki/Ephemeral_port). In particular, these ports are used by RPC, which is an integral part or Windows - several Windows components communicate with each other using RPC. Maybe this might be a reason why you see problems with those ports.
I my test I was not able to open port 50000 in the beginning - it was already in use.

Could you repeat your test on your system with some port between 1024 and 32000? Maybe 20000-20150 like I did?

**Comment by bel2125** [comment] 2015-06-22 19:03
The range of ephemeral ports depends on the windows version. Up to XP it was 1024 to 5000, from Vista on it is 49152 to 65535 (https://support2.microsoft.com/default.aspx?scid=kb;EN-US;929851). You can check it for your system with
`netsh int ipv4 show dynamicport tcp`

On my Windows system, port 50000 can not be used, so I could only use port 50001 to 50160.
I do not see any problems in this test after some hours.

Can you check with netstat (https://technet.microsoft.com/en-us/library/bb490947.aspx - or PortReporter https://www.microsoft.com/en-us/download/details.aspx?id=9964) what ports are used right when when you start the servers and an hour later after the problem occurred.
`netstat -ano | find "TCP"`  will show the port number and the process ID.
Does netstat confirm the process used an additional or different port?

**Comment by bel2125** [comment] 2015-06-22 19:09
Did you check if the problem also occurs with the default CivetWeb executable? Or does it occur only if embedded into your application?

Currently I can not reproduce your problem, so I can not analyze it in more depth.
I need some more information from you.

**Comment by bel2125** [comment] 2015-07-14 13:06
@hanrobin123: Is this problem still observed when you use the current version and use ports not in the ephemeral port range?

I would like to either continue analyzing this issue with more information, or close it if it is no longer relevant.

**Comment by hanrobin123** [comment] 2015-07-17 14:48
Hi:

This issue was resolved. We will let OS allocate an available port number for our web server instead of  specify a port number to bind.
That will fix the port number conflict issue when launching lots of web server on the same machine.
Anyway thanks for your attention and helps.

Thank you,
robin

**Closed** 2015-07-17 19:24 UTC
